#!/usr/bin/env ruby

require File.dirname(__FILE__) + '/../config/environment'

require 'rubygems'
require 'activerecord'
require 'yaml'

class Post < ActiveRecord::Base; end
class User < ActiveRecord::Base; end

lacho = User.find_by_nick_name("lachlanhardy")
raise "Lachlan doesnt exist! Odd eh." unless lacho

YAML.load(File.open(File.dirname(__FILE__) + "/blog_posts.yml").read).each do |post|
  Post.create :user => lacho,
              :title => post[:title],
              :body  => post[:body],
              :permalink => post[:permalink],
              :published_at => (Time.parse(post[:published_at]) - 10.hours)
end
